export class companias {
    public prm_companias = {
        token: JSON.parse(decodeURIComponent(escape(window.atob(localStorage._token)))),
        accion_tipo: '',
        id_compania: parseInt(localStorage.getItem("COMP")),
        id_provincia: 0,
        id_distrito: 0,
        nombre: '',
        gerente: '',
        sub_gerente: '',
        codigo_postal: '',
        direccion: '',
        correo: '',
        impuesto: 0,
        pagina_web: '',
        descripcion: '',
        fecha_crea: new Date().toUTCString(),
        usuario_crea: parseInt(localStorage.getItem("USU")),
        usuario_actualiza: parseInt(localStorage.getItem("USU")),
        fecha_actualiza: new Date().toUTCString(),
        sw_activo: 0,
        telefono: '',
        id_pais: 0,
        longitud: '',
        latitud: '',
        nombre_pais: '',
        longitud_pais: '',
        latitud_pais: '',
        sw_activo_pais: 0,
        id_pais_provincia: 0,
        nombre_provincia: '',
        longitud_provincia: '',
        latitud_provincia: '',
        sw_activo_provincia: 0,
        id_forma_pago: 0,
        sw_rfid: 0,
        tag_rfid: '',
        contacto: ''
        
    }
}