export class control_usuarios {
    public prm_control_usuarios = {
        token: JSON.parse(decodeURIComponent(escape(window.atob(localStorage._token)))),
        accion_tipo: '',
        id_compania: parseInt(localStorage.getItem("COMP")),
        id_menu: 0,
        id_padre: 0,
        nombre_menu: '',
        link: '',
        sw_contenedor: 0,
        fecha_crea: new Date().toUTCString(),
        usuario_crea: parseInt(localStorage.getItem("USU")),
        usuario_actualiza: parseInt(localStorage.getItem("USU")),
        fecha_actualiza: new Date().toUTCString(),
        sw_activo: 0,
        id_rol: 0,
        id_permiso: 0,
        nombre_rol: '',
        descripcion: '',
        sw_crea: 0,
        sw_eliminar: 0,
        sw_editar: 0,
        sw_deshabilita: 0,
        sw_principal: 0,
        id_usuario: 0,
        nombre_usuario: '',
        apellido: '',
        identidad_personal: '',
        fecha_de_nacimiento: new Date().toUTCString(),
        usuario: '',
        contrasena: '',
        direccion: '',
        funciones: '',
        correo: '',
        telefono: '',
        foto: '',
        tipo_img: '',
        fecha_inicio: new Date().toUTCString(),
        sw_mostrar: 1,
        Tipo_de_licencia: "",
        cambio_contrasena: 0,
        id_tipo_personal: 0,
        genero: '',
        nombre: '',
        id_licencia: 0,
        sistemas: '',
        id_clase: 0,
        id_sistema:0,
        sw_super_admin: parseInt(localStorage.getItem("sadm")),
        url_origin:''
    }
}