export class inventarios {
    public prm_inventarios = {
        token: JSON.parse(decodeURIComponent(escape(window.atob(localStorage._token)))),
        accion_tipo: '',
        id_compania: parseInt(localStorage.getItem("COMP")),
        id_almacen: 0,
        id_parte: 0,
        id_proveedor: 0,
        id_fabricante: 0,
        id_ubicacion: 0,
        cant_disponible: 0,
        cant_autorizada: 0,
        min_permitida: 0,
        precio_unitario: 0,
        precio_unitario_base: 0,
        descripcion: '',
        fecha_crea: new Date().toUTCString(),
        fecha_actualiza: new Date().toUTCString(),
        sw_activo: 0,
        id_almacen_compania: 0,
        id_parte_compania: 0,
        id_distrito: 0,
        sw_reparable: 0,
        sw_esencial: 0,
        sw_entrega: 0,
        sw_proveedor: 0,
        nombre: '',
        inicial: '',
        sw_tipo_entrega: 0,
        id_pais: 0,
        id_provincia: 0,
        domicilio: '',
        nombre_contacto: '',
        telefono: '',
        codigo_postal: '',
        correo: '',
        pagina_web: '',
        sw_rfid: 0,
        cod_rfid: '',
        id_unidad: 0,
        tag_rfid: '',
        disponible: 0,
        unidad_entrega: 0,
        unidad_proveedor: 0,
        ruc: '',
        id_forma_pago: 0,
        manejo_de_envio: 0,
        id_deficiencia: 0,
        id_unidad_entrega: 0,
        id_unidad_proveedor: 0,
        usuario_crea: parseInt(localStorage.getItem("USU")),
        usuario_actualiza: parseInt(localStorage.getItem("USU")),
    }
}